# -*- coding: utf-8 -*-
"""SCT_DS_2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Gu-CzZpo2c9HFgZeUZU7XSKmoM0LRq2g

**MAIN CODE**
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from google.colab import files

# %matplotlib inline

uploaded = files.upload()
df = pd.read_csv("train.csv")

df['Age'] = df['Age'].fillna(df['Age'].median())
df['Embarked'] = df['Embarked'].fillna(df['Embarked'].mode()[0])
df['HasCabin'] = df['Cabin'].notnull().astype(int)
df = df.drop(columns=['Cabin'])

df['Age'].hist(bins=20, edgecolor='black', color='darkblue')
plt.xlabel("Age")
plt.ylabel("Count")
plt.title("Age Distribution", fontweight='bold')
plt.show()

ax = df['Survived'].value_counts().plot(kind='bar', color='darkred')
plt.xticks([0,1], ['Not Survived','Survived'], rotation=0)
plt.title("Survival Count", fontweight='bold')
plt.ylabel("Number of Passengers")
for p in ax.patches:
    ax.annotate(str(p.get_height()), (p.get_x()+0.1, p.get_height()+5))
plt.show()

ax = df.groupby('Sex')['Survived'].mean().plot(kind='bar', color='darkgreen')
plt.title("Survival Rate by Sex", fontweight='bold')
plt.ylabel("Survival Rate")
for p in ax.patches:
    ax.annotate(f"{p.get_height():.2f}", (p.get_x()+0.1, p.get_height()+0.01))
plt.show()

ax = df.groupby('Pclass')['Survived'].mean().plot(kind='bar', color='purple')
plt.title("Survival Rate by Passenger Class", fontweight='bold')
plt.ylabel("Survival Rate")
for p in ax.patches:
    ax.annotate(f"{p.get_height():.2f}", (p.get_x()+0.1, p.get_height()+0.01))
plt.show()

ax = df.groupby('Embarked')['Survived'].mean().plot(kind='bar', color='orange')
plt.title("Survival Rate by Embarked Port", fontweight='bold')
plt.ylabel("Survival Rate")
for p in ax.patches:
    ax.annotate(f"{p.get_height():.2f}", (p.get_x()+0.05, p.get_height()+0.01))
plt.show()